### ISSUE TITLE
Fetch cards from a GitHub projects board

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/github-projects-automation#1]
```[tasklist]
### Tasks
- [ ] Investigate the GraphQL method to fetch cards from a GitHub board
- [x] Ask Ashish for the IMPACT board to use when doing this
- [ ] Fetch cards from the board as a JSON
- [ ] Be able to filter cards based on Status
- [ ] Be able to filter cards based on Estimate
- [ ] Be able to filter cards based on any other metadata
```

**Comment by SauravUpadhyaya** [comment]
Here is the code:
https://github.com/NASA-IMPACT/github-projects-automation/tree/1-fetch-cards-from-a-github-projects-board
