### ISSUE TITLE
Investigate whether similar Python packages already exist and borrow code where we can

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/github-projects-automation#12]
Before we start doing anything, we want to make sure we reuse where we can. We want to study what already exists out there so we can make better decisions as to what we can functionality we can borrow and what we need to build ourselves.

```[tasklist]
### Tasks
- [ ] Do a thorough search of GitHub for python packages that deal with Projects V2 using GraphQL
- [ ] Briefly read through the code of each one
- [ ] Make a list of these packages with links to documentation
```
