### ISSUE TITLE
Set up a dev environment with modern Python

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/github-projects-automation#14]
In order to make this project as up to date as possible, we would like to start with good development practices in modern Python.

```[tasklist]
### Tasks
- [ ] Set up an environment with the latest version of Python
- [ ] Add pre-commit hooks 
- [ ] Add mypy validation
- [ ] Add pytest
- [ ] Make sure all code has type hints and is tested
```
