### ISSUE TITLE
Successfully authenticate with GitHub GraphQL using a Personal Access Token from a bot account

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/github-projects-automation#2]
```[tasklist]
### Tasks
- [x] Ask Ashish for the Personal Access Token
- [ ] Ask Ashish for starter Jupyter notebook
- [ ] Learn how you can authenticate using a personal access token
- [ ] Validate that authentication is successful
```
