### ISSUE TITLE
Fetch issues from a repo with GraphQL

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/github-projects-automation#3]
```[tasklist]
### Tasks
- [ ] Given a repository, be able to fetch its issues using GraphQL
- [ ] Learn about GitHub's issue filtering syntax
- [ ] Filter issues based on various conditions
```

**Comment by SauravUpadhyaya** [comment]
Here is the code:
https://github.com/NASA-IMPACT/github-projects-automation/tree/11-add-metrics-from-the-sde-board-on-the-sample-project-board
