### ISSUE TITLE
Update the metadata on an issue with GraphQL

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/github-projects-automation#4]
```[tasklist]
### Tasks
- [ ] Given an issue number, fetch the issue
- [ ] Update the assignee
- [ ] Update the milestone
- [ ] Update labels
- [ ] Make a list of metadata that can be updated and add it on this card
```

**Comment by SauravUpadhyaya** [comment]
Here is the code:
https://github.com/NASA-IMPACT/github-projects-automation/tree/11-add-metrics-from-the-sde-board-on-the-sample-project-board
