### ISSUE TITLE
Comment on an issue with GraphQL

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/github-projects-automation#5]
```[tasklist]
### Tasks
- [ ] Given an issue, be able to fetch its comments as a JSON
- [ ] Write a new comment to the issue with GraphQL
- [ ] Add the function to the package
- [ ] Write tests for the function
```

**Comment by SauravUpadhyaya** [comment]
Here is the code:
https://github.com/NASA-IMPACT/github-projects-automation/tree/11-add-metrics-from-the-sde-board-on-the-sample-project-board
